/*
 * SimpleKPI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package simplekpi

type KpiEntry struct {
	// The actual value cannot be null if the target and notes are both null
	Actual float64 `json:"actual,omitempty"`
	// The UTC date and time the KPI entry was created. Date time format without timezone, e.g. `2019-01-01T00:00:00`
	CreatedAt string `json:"created_at,omitempty"`
	// The date of the entry. Date time format without timezone, e.g. `2019-01-01T00:00:00`
	EntryDate string `json:"entry_date"`
	// Automatically generated for the KPI entry
	Id int64 `json:"id,omitempty"`
	// The kpi must be active and cannot be a calculated KPI. The KPI must also be assigned to the user
	KpiId int64 `json:"kpi_id"`
	// The note associated with the KPI entry
	Notes string `json:"notes,omitempty"`
	// The target value of the entry. This value will be ignored if the KPI has a null target
	Target float64 `json:"target,omitempty"`
	// The UTC date and time the KPI entry was updated. Date time format without timezone, e.g. `2019-01-01T00:00:00`
	UpdatedAt string `json:"updated_at,omitempty"`
	// An id of an active user to assign to the KPI entry
	UserId int64 `json:"user_id"`
}
