/*
 * SimpleKPI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package simplekpi

type User struct {
	CanAdminSettings      bool   `json:"can_admin_settings,omitempty"`
	CanManageUsers        bool   `json:"can_manage_users,omitempty"`
	CreatedAt             string `json:"created_at,omitempty"`
	Email                 string `json:"email,omitempty"`
	FirstName             string `json:"first_name,omitempty"`
	Id                    int64  `json:"id,omitempty"`
	LastLoginAt           string `json:"last_login_at,omitempty"`
	LastName              string `json:"last_name,omitempty"`
	LastPasswordChangedAt string `json:"last_password_changed_at,omitempty"`
	Password              string `json:"password,omitempty"`
	UpdatedAt             string `json:"updated_at,omitempty"`
	UserStatusId          string `json:"user_status_id,omitempty"`
	UserType              string `json:"user_type,omitempty"`
}
