/*
 * SimpleKPI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package simplekpi

type Kpi struct {
	AggregateFunction string  `json:"aggregate_function,omitempty"`
	CategoryId        int64   `json:"category_id,omitempty"`
	CreatedAt         string  `json:"created_at,omitempty"`
	Description       string  `json:"description,omitempty"`
	FrequencyId       string  `json:"frequency_id,omitempty"`
	IconId            int64   `json:"icon_id,omitempty"`
	Id                int64   `json:"id,omitempty"`
	IsActive          bool    `json:"is_active,omitempty"`
	IsCalculated      bool    `json:"is_calculated,omitempty"`
	Name              string  `json:"name,omitempty"`
	SortOrder         int32   `json:"sort_order,omitempty"`
	TargetDefault     float32 `json:"target_default,omitempty"`
	UnitId            int64   `json:"unit_id,omitempty"`
	UpdatedAt         string  `json:"updated_at,omitempty"`
	ValueDirection    string  `json:"value_direction,omitempty"`
}
